name = "copa-haxel"
compatibility_date = "2024-03-20"
pages_build_output_dir = "dist/client"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "copa-haxel-db"
database_id = "YOUR_DATABASE_ID"
